[package]
name = "consensus-atlas-raftrs-worker"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
base64 = "=0.22.1"
protobuf = "=2.28.0"
raft = { version = "=0.7.0", default-features = false, features = ["protobuf-codec"] }
serde = { version = "=1.0.219", features = ["derive"] }
serde_json = "=1.0.140"
sha2 = "=0.10.8"
slog = "=2.7.0"
